### ISSUE TITLE
Missing RTX4090

### ISSUE THREAD

**Issue by brayevalerien** [mlco2/impact#48]
As the title says, the RTX 4090 is not available in the hardware type list, even though it is a very common card for image generation for instance.
It would be great to add the data to support this GPU.

**Comment by IamLRBA** [comment]
@brayevalerien the RTX 4090 is already present in the file. Here's the existing entry for the RTX 4090:
`RTX 4090,gpu,300,82.6,82.6,NaN,NaN,24,https://images.nvidia.com/aem-dam/Solutions/Data-Center/l4/nvidia-ada-gpu-architecture-whitepaper-v2.1.pdf`

If this entry is accurate and complete, there's no additional action required in the file. However, if you need I would like to adjust or add more details to this entry (such as GFLOPS32/W or GFLOPS16/W), to update it.

I will provide a PR just in case it is required.
Thanks!

**Comment by brayevalerien** [comment]
Ah, looks correct. Thanks a lot.

**Comment by IamLRBA** [comment]
> Ah, looks correct. Thanks a lot.

You're welcome, if there's anything else I can do please let me know.
